#!/usr/bin/env node
// Generates src/contracts.gen.ts from the JSON Schemas in contracts/, so a
// contract change breaks the TypeScript build wherever it matters.
// tests/contracts.test.ts fails if the committed file is stale.
//
//   node scripts/gen-types.mjs           write src/contracts.gen.ts

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "contracts.gen.ts");

// [schema file, $defs to export as named types (none = the schema's root)]
const SOURCES = [
  ["core-program", []],
  ["ask", ["request", "answer"]],
  ["fakes", ["answers", "commands"]],
  ["event", []],
];

const pascal = (s) => s.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase());

export async function generate() {
  const parts = ["// Generated by scripts/gen-types.mjs from contracts/*.schema.json. Don't edit.\n"];
  for (const [file, defs] of SOURCES) {
    const schema = JSON.parse(readFileSync(join(ROOT, "contracts", `${file}.schema.json`), "utf8"));
    const targets =
      defs.length === 0
        ? [[schema.title, schema]]
        : defs.map((d) => [`${pascal(file)}${pascal(d)}`, { ...schema.$defs[d], $defs: schema.$defs }]);
    for (const [name, s] of targets) {
      parts.push(
        await compile({ ...s, title: name }, name, {
          bannerComment: "",
          additionalProperties: false,
          unreachableDefinitions: false,
          style: { printWidth: 140 },
        }),
      );
    }
  }
  // Data the runtime needs from the contracts, so the built CLI never reads contracts/ (it isn't shipped).
  const codes = JSON.parse(readFileSync(join(ROOT, "contracts", "error-codes.json"), "utf8"));
  const meanings = Object.fromEntries(codes.map((c) => [c.code, c.meaning]));
  parts.push(`/** SPEC §7.1: each error and warning code's meaning, from contracts/error-codes.json. */
export const CODE_MEANINGS: Record<string, string> = ${JSON.stringify(meanings, null, 2)};
`);
  const fakes = readFileSync(join(ROOT, "contracts", "fakes.schema.json"), "utf8");
  parts.push(`/** contracts/fakes.schema.json, which --fake and --fake-exec files are checked against (SPEC §7.1 E-CONFIG). */
export const FAKES_SCHEMA = ${JSON.stringify(JSON.parse(fakes), null, 2)};
`);
  return parts.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) writeFileSync(OUT, await generate());
