#!/usr/bin/env node
// Generates src/skill.gen.ts from skills/write-skope-skill/SKILL.md, so the
// skill ships inside every build, the standalone binary included, and
// `skope --install-skill` can write it out. tests/install-skill.test.ts
// fails if the committed file is stale.
//
//   node scripts/gen-skill.mjs           write src/skill.gen.ts

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src", "skill.gen.ts");

export function generate() {
  const text = readFileSync(join(ROOT, "skills", "write-skope-skill", "SKILL.md"), "utf8");
  return `// Generated by scripts/gen-skill.mjs from skills/write-skope-skill/SKILL.md. Don't edit.\nexport const WRITE_SKOPE_SKILL = ${JSON.stringify(text)};\n`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) writeFileSync(OUT, generate());
