// Generated by scripts/gen-types.mjs from contracts/*.schema.json. Don't edit.

/**
 * `s:` plus the section's slug (SPEC §3.4): lowercased, every run of characters that aren't letters or digits turned into one `_`.
 */
export type SectionId = string;
export type Src = number;
export type ParamValue =
  | {
      str: string;
      src: Src;
    }
  | {
      int: number;
      src: Src;
    };
export type Stmt = StmtRun | StmtDo | StmtCheck | StmtAsk | StmtForEach | StmtIfYes | StmtThen | StmtPage | StmtHandOff | StmtStop;
export type Name = string;
/**
 * Text split into literal and variable parts, so the core never scans for `{`. How a variable is shown in a question is decided by the core from its value's origin (SPEC §3.5).
 */
export type Parts = (
  | {
      lit: string;
    }
  | {
      var: Name;
    }
)[];
/**
 * null when there's no else.
 */
export type Else =
  | null
  | {
      skip: {};
    }
  | SectionRef;
/**
 * A command, or `item`: the name of a for-each variable over action items (`do step`).
 */
export type DoBody =
  | {
      cmd: Parts;
    }
  | {
      item: Name;
    };
export type Cond =
  | {
      succeeds: Parts;
    }
  | {
      cmp: {
        op: "<" | "<=" | ">" | ">=" | "==" | "!=";
        l: Operand;
        r: Operand;
      };
    };
export type Operand =
  | {
      var: Name;
    }
  | {
      /**
       * Decimal as written; a trailing % is dropped (SPEC §3.4).
       */
      num: string;
    };
export type Target =
  | {
      stop: {};
    }
  | SectionRef;
export type Body = Stmt[];

/**
 * Core program JSON (SPEC §5.1): what the preprocessor emits and the Dafny core consumes. The preprocessor only parses; every semantic check (references resolve, taint, bound names, ...) is the core's job, so this schema accepts programs that will fail lint. `src` is always the 1-based line in SKILL.md.
 */
export interface CoreProgram {
  skill: string;
  format: 1;
  /**
   * The `entry:` frontmatter value and its line; when defaulted, the first instruction section and its heading line.
   */
  entry: {
    section: SectionId;
    src: Src;
  };
  params: {
    [k: string]: ParamValue;
  };
  limits: {
    run_timeout_ms: number;
    do_timeout_ms: number;
    deadline_ms: number;
    ask_context_tokens: number;
  };
  /**
   * Every ## section (SPEC §5.1), by id. An instruction section has a body; any other section has its lists.
   */
  sections: {
    [k: string]: Section | OtherSection;
  };
}
export interface Section {
  /**
   * Display name, as written in the heading.
   */
  name: string;
  src: Src;
  /**
   * SPEC §3.2.
   */
  guidance: string | null;
  body: Body;
}
export interface StmtRun {
  src: Src;
  run: RunBody;
  else: Else;
}
export interface RunBody {
  cmd: Parts;
  as?: Name;
}
/**
 * A reference to a section. `anchor` is present only for a real link `[text](#anchor)`: `given` is the anchor written; `expected` is the GitHub slug of the heading of the section the link text resolves to (SPEC §3.4), or of the link text itself when it resolves to no section. The core reports E-UNRESOLVED if they differ.
 */
export interface SectionRef {
  section: SectionId;
  anchor?: Anchor;
}
export interface Anchor {
  given: string;
  expected: string;
}
export interface StmtDo {
  src: Src;
  do: DoBody;
  else: Else;
}
/**
 * `then` is null for the `check COND else …` form (SPEC §4.2), which then needs an else.
 */
export interface StmtCheck {
  src: Src;
  check: {
    cond: Cond;
    then: null | Target;
    else: Else;
  };
}
export interface StmtAsk {
  src: Src;
  ask: Ask;
}
/**
 * Exactly one of sections, yesno, one_of or score (SPEC §3.4, §4.7).
 */
export interface Ask {
  question: Parts;
  sure: number;
  else: Else;
  sections?: {
    src: Src;
    section: SectionId;
    anchor?: Anchor;
  }[];
  yesno?: {
    /**
     * `_yn` when the skill doesn't name it.
     */
    as: string;
  };
  one_of?: {
    list: SectionRef;
    as: Name;
  };
  /**
   * v1.1.
   */
  score?: {
    low: number;
    high: number;
    rubric: {
      src: Src;
      level: number;
      text: string;
    }[];
    as: Name;
  };
}
export interface StmtForEach {
  src: Src;
  for_each: {
    var: Name;
    list: SectionRef;
    body: Body;
  };
}
export interface StmtIfYes {
  src: Src;
  /**
   * Exactly one of run or do.
   */
  if_yes: {
    /**
     * INLINE has no `as` (SPEC §3.4).
     */
    run?: {
      cmd: Parts;
    };
    do?: DoBody;
    else: Else;
  };
}
export interface StmtThen {
  src: Src;
  then: SectionRef;
}
export interface StmtPage {
  src: Src;
  page: Parts;
}
export interface StmtHandOff {
  src: Src;
  hand_off: {};
}
export interface StmtStop {
  src: Src;
  stop: {};
}
/**
 * A section with no instructions: a data section, or prose. Used as a list only if it has exactly one list (E-SECTION-KIND otherwise).
 */
export interface OtherSection {
  /**
   * Display name, as written in the heading.
   */
  name: string;
  src: Src;
  lists: List[];
}
/**
 * One Markdown list in a non-instruction section. `src` is its first item's line.
 */
export interface List {
  src: Src;
  items: (
    | {
        src: Src;
        action: {
          label: string;
          cmd: Parts;
        };
      }
    | {
        src: Src;
        value: string;
      }
  )[];
}

export interface AskRequest {
  kind: "choice" | "yesno" | "score";
  /**
   * Rendered: trusted values pasted in, run outputs named in backticks (SPEC §3.5).
   */
  question: string;
  guidance: string | null;
  /**
   * @minItems 2
   */
  options: [
    {
      id: string;
      label: string;
      description: string | null;
    },
    {
      id: string;
      label: string;
      description: string | null;
    },
    ...{
      id: string;
      label: string;
      description: string | null;
    }[]
  ];
  /**
   * Exactly the run outputs the question names, redacted and truncated (SPEC §6.3).
   */
  context: {
    [k: string]: string;
  };
  timeout_ms: number;
}

export interface AskAnswer {
  probs: {
    [k: string]: number;
  };
  unassigned?: number;
  backend: string;
  model: string;
  ms: number;
}

/**
 * answers.yaml. A probs object keyed by option id, with optional `unassigned`, is passed to the core as the backend's answer, valid or not. `unsure` is a uniform answer over the options, which is always a tie, so the gate fails. `unavailable` is a backend failure (ask_unavailable).
 */
export interface FakesAnswers {
  [k: string]:
    | ("unsure" | "unavailable")
    | {
        [k: string]: number;
      };
}

/**
 * commands.yaml: how each command ends. A list is used in order, one result per run of the command, with the last repeating: a loop that re-reads usage can see it fall. An unmatched command is E-FAKE-UNMATCHED; no real command ever runs.
 */
export interface FakesCommands {
  [k: string]: Result | [Result, ...Result[]];
}
export interface Result {
  /**
   * null when it timed out.
   */
  exit: number | null;
  stdout?: string;
  stderr?: string;
  timed_out?: boolean;
  /**
   * Simulated duration. Under --fake-exec the host's clock advances by it, so deadline scenarios can be written.
   */
  ms?: number;
}

/**
 * One line of skope's JSON Lines output on stdout (SPEC §10). Exactly one event shape matches, chosen by `event`. Every shape has the common fields ts, run_id, skill, skill_hash, host, and optionally section and line; run_id, skill and skill_hash are null before a run exists. Nothing else is allowed.
 */
export type Event =
  | RunStartEvent
  | RunEvent
  | CheckCmdEvent
  | CheckEvent
  | AskEvent
  | EffectStartEvent
  | EffectEndEvent
  | WouldDoEvent
  | PageEvent
  | WouldPageEvent
  | HandoffPageEvent
  | TransferEvent
  | OutcomeEvent
  | HandoffRecordEvent
  | ErrorEvent
  | WarningEvent
  | LockedEvent
  | StaleLockEvent;

/**
 * The run began.
 */
export interface RunStartEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "run_start";
  params: {
    [k: string]: string;
  };
  dry_run: boolean;
  caller: "person" | "agent";
  run_dir: string;
  skope_version: string;
  /**
   * Build identity, bare hex (SPEC §7.2).
   */
  skope_build: string;
}
/**
 * A run command finished.
 */
export interface RunEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "run";
  cmd: string;
  /**
   * null when the command timed out or was killed.
   */
  exit: number | null;
  ms: number;
  timed_out: boolean;
  truncated: boolean;
  stdout_hash: string;
  /**
   * Redacted, at most 2KB.
   */
  stdout_tail: string;
  after_would_do: boolean;
}
/**
 * A command check finished.
 */
export interface CheckCmdEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "check_cmd";
  cmd: string;
  /**
   * null when the command timed out or was killed.
   */
  exit: number | null;
  ms: number;
  timed_out: boolean;
  truncated: boolean;
  stdout_hash: string;
  /**
   * Redacted, at most 2KB.
   */
  stdout_tail: string;
  after_would_do: boolean;
}
/**
 * A comparison was evaluated.
 */
export interface CheckEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "check";
  expr: string;
  left: string | null;
  right: string | null;
  result: boolean | null;
  after_would_do: boolean;
}
/**
 * A question was asked. probs, chosen and confidence are null when the backend failed; detail then says why.
 */
export interface AskEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "ask";
  question: string;
  kind: "choice" | "yesno" | "score";
  probs: {
    [k: string]: number;
  } | null;
  chosen: string | number | null;
  confidence: number | null;
  sure: number;
  passed: boolean;
  backend: string;
  model: string;
  ms: number;
  request_path: string;
  request_sha256: string;
  after_would_do: boolean;
  /**
   * Score asks only.
   *
   * @minItems 2
   * @maxItems 2
   */
  range?: [number, number];
  /**
   * Failed asks only.
   */
  detail?: "unavailable" | "request_too_large";
}
/**
 * A do command is about to run.
 */
export interface EffectStartEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "effect_start";
  cmd: string;
}
/**
 * A do command finished.
 */
export interface EffectEndEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "effect_end";
  cmd: string;
  /**
   * null when the command timed out or was killed.
   */
  exit: number | null;
  ms: number;
  timed_out: boolean;
}
/**
 * Dry run: a do command that didn't run.
 */
export interface WouldDoEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "would_do";
  cmd: string;
}
/**
 * A page instruction paged a human.
 */
export interface PageEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "page";
  text: string;
  /**
   * Did the pager command succeed.
   */
  ok: boolean;
}
/**
 * Dry run: a page that wasn't sent.
 */
export interface WouldPageEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "would_page";
  text: string;
}
/**
 * The page sent for a handoff (SPEC §8).
 */
export interface HandoffPageEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "handoff_page";
  text: string;
  ok: boolean;
}
/**
 * The run moved to another section.
 */
export interface TransferEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "transfer";
  from: string;
  to: string;
}
/**
 * The run ended. Always the last event.
 */
export interface OutcomeEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "outcome";
  outcome: "stopped" | "paged" | "handoff" | "locked" | "stale_lock" | "invalid" | "error";
  /**
   * A handoff reason (SPEC §8.1), or null.
   */
  reason: "explicit" | "gate_failed" | "command_failed" | "ask_unavailable" | "deadline" | null;
  ask_calls: number;
  effects: number;
  /**
   * null if the mode was never set.
   */
  dry_run: boolean | null;
}
/**
 * The handoff record was written.
 */
export interface HandoffRecordEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "handoff_record";
  path: string;
  record: {};
}
/**
 * An error (SPEC §7.1).
 */
export interface ErrorEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "error";
  code: string;
  stage: "parse" | "lint" | "args" | "runtime";
  file?: string;
  message: string;
}
/**
 * A warning (SPEC §7.1). stage is the stage that found it.
 */
export interface WarningEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "warning";
  code: string;
  stage: "parse" | "lint" | "args" | "runtime";
  file?: string;
  message: string;
}
/**
 * Another run holds the lock.
 */
export interface LockedEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "locked";
  holder_pid: number;
}
/**
 * An earlier run died holding the lock.
 */
export interface StaleLockEvent {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  /**
   * null before a run exists.
   */
  run_id: string | null;
  /**
   * null before a run exists.
   */
  skill: string | null;
  /**
   * null before a run exists.
   */
  skill_hash: string | null;
  host: string;
  /**
   * The section's display name.
   */
  section?: string;
  line?: number;
  event: "stale_lock";
  path: string;
  /**
   * null when the lock can't be read or parsed (SPEC §7).
   */
  holder_pid: number | null;
}

/** SPEC §7.1: each error and warning code's meaning, from contracts/error-codes.json. */
export const CODE_MEANINGS: Record<string, string> = {
  "E-NOT-RUNNABLE": "no `format: 1` in the frontmatter (§3.1)",
  "E-FRONTMATTER": "a frontmatter field is missing or invalid",
  "E-DUP-SECTION": "two sections have the same slug (§3.4)",
  "E-SECTION-KIND": "a section used as a list doesn't contain exactly one list (§3.2)",
  "E-MISPLACED": "a list item starting with a keyword where instructions aren't recognised (§3.3 rule 7)",
  "E-SECTION-NAME": "a `##` heading has no letters or digits, so it has no slug (§3.2)",
  "E-DATA-ITEM": "a data list item isn't a plain-text value or ``Label — `command` `` (§3.6)",
  "E-UNKNOWN-BOLD": "bold text that isn't a keyword and doesn't end in `:`, including a misspelled keyword (§3.3 rules 3 and 5)",
  "E-GRAMMAR": "a keyword item doesn't match §3.4",
  "E-NESTED-LIST": "a nested list under an instruction that doesn't take one",
  "E-OPTION-ITEM": "an option item isn't exactly one `[Section]` link",
  "E-RUBRIC-ITEM": "a rubric line isn't `INT: text` (v1.1)",
  "E-UNRESOLVED": "a `[Section]` or `[List]` reference doesn't resolve",
  "E-REF-KIND": "a data section used as a target, or an instruction section used as a list",
  "E-CYCLE": "the transfer graph has a cycle (§4.6)",
  "E-FALLS-OFF": "a path reaches the end of a section without ending or transferring",
  "E-UNREACHABLE": "an instruction can never run (§4.1)",
  "E-TAINT": "an untrusted value in a command (§3.5)",
  "E-ACTION-IN-CMD": "an action item interpolated into a command (§3.5)",
  "E-UNSAFE-VALUE": "a param default or value item reaching a command fails the safe-value check",
  "E-UNBOUND": "a name in a command or comparison may be unbound, is never bound, or is out of scope",
  "E-IF-YES": "`if yes` has no governing `yes | no` ask (§4.2)",
  "E-ELSE-SKIP": "`else skip` where it isn't allowed",
  "E-OPTION-COUNT": "a section-option ask has fewer than 2 or more than 255 options",
  "E-LIST-KIND": "the wrong kind of list for the instruction",
  "E-LIST-EMPTY": "a data list has no items",
  "E-LIST-MIXED": "a data list mixes action and value items",
  "E-LIST-DUP": "two items in a data list have the same label, ignoring case (§3.6)",
  "E-SCORE-RANGE": "Score bounds invalid, or not 2–10 levels (v1.1)",
  "E-SCORE-RUBRIC": "Score rubric missing, incomplete, out of range or duplicated (v1.1)",
  "E-USAGE": "an unknown flag, a missing or malformed flag value, a missing or unreadable skill path, or an unreadable or malformed `--trace` file (§7)",
  "E-MODE": "neither or both of `--apply` and `--dry-run` (§7 step 0)",
  "E-PARAM-UNKNOWN": "`--param` names a param the skill doesn't declare",
  "E-PARAM-TYPE": "a `--param` value has the wrong type",
  "E-PARAM-UNSAFE": "a param override or built-in fails the safe-value check",
  "E-CONFIG": "the config file, or a `--fake` or `--fake-exec` file, is unreadable or invalid (fake files are checked against `contracts/fakes.schema.json` before the run)",
  "E-BACKEND-MODEL": "the `openrouter` model doesn't support logprobs, or its reasoning can't be turned off (§6.2)",
  "E-BACKEND-LIMIT": "the skill exceeds the configured backend's limits: options, Score levels or context (§6.2)",
  "E-FAKE-UNMATCHED": "`--fake-exec` has no answer for a command, or `--fake` has none for a question (§5.4)",
  "E-FAKE-AMBIGUOUS": "a `Section.var` or `Section.ask` fake key names more than one statement (§5.4)",
  "E-IO": "skope can't write its run directory or lock file",
  "E-INTERRUPTED": "skope was interrupted (SIGINT or SIGTERM); it stopped the running command and released the lock (§4.4)",
  "E-INTERNAL": "a runner bug. Unreachable by P6, so always a bug report",
  "W-SCORE-THRESHOLD": "a Score variable is only used in one comparison against one threshold; a `yes | no` ask gates more reliably (v1.1)",
  "W-SCORE-UNUSED": "a Score variable is never used after it's bound (v1.1)",
  "W-SECTION-UNREACHED": "no path reaches a section (§5.6)",
  "W-ASK-NO-CONTEXT": "an `ask` question names nothing that could hold `run` output, so the model gets no evidence (§6.3)",
  "W-MODEL-ALIAS": "`jev.model` is an alias, or a response came from a different model than configured (§6.2)",
  "W-NO-GUIDANCE": "a section offered as an `ask` option has no guidance paragraph (§3.2)",
  "W-CONFIG-PERMS": "the config file is group-writable or owned by someone other than this user or root; `pager.command` runs through `sh`, so whoever can write the file can run commands (§9). A world-writable config is `E-CONFIG`.",
  "W-REDACT-OFF": "built-in redaction patterns are turned off (§9)",
  "W-FAKE-UNUSED": "a fake key names no statement: a `line:N` with nothing on that line, or a `Section.var` / `Section.ask` the section doesn't have (§5.4)"
};
