// Generated by scripts/gen-types.mjs from contracts/*.schema.json. Don't edit.

/**
 * `s:` plus the slugified section name: lowercase, runs of other characters become `_`.
 */
export type SectionId = string;
export type ParamValue =
  | {
      str: string;
    }
  | {
      int: number;
    };
export type Src = number;
export type Name = string;
/**
 * Text split into literal and variable parts, so the core never scans for `{`. How a variable is shown in a question is decided by the core from its value's origin (SPEC §3.5).
 */
export type Parts = (
  | {
      lit: string;
    }
  | {
      var: Name;
    }
)[];
export type Stmt = StmtRun | StmtDo | StmtCheck | StmtAsk | StmtForEach | StmtIfYes | StmtThen | StmtPage | StmtHandOff | StmtStop;
/**
 * null when there's no else.
 */
export type Else =
  | null
  | {
      skip: {};
    }
  | SectionRef;
/**
 * A command, or `item`: the name of a for-each variable over action items (`do step`).
 */
export type DoBody =
  | {
      cmd: Parts;
    }
  | {
      item: Name;
    };
export type Cond =
  | {
      succeeds: Parts;
    }
  | {
      cmp: {
        op: "<" | "<=" | ">" | ">=" | "==" | "!=";
        l: Operand;
        r: Operand;
      };
    };
export type Operand =
  | {
      var: Name;
    }
  | {
      /**
       * Decimal as written; a trailing % is dropped (SPEC §3.4).
       */
      num: string;
    };
export type Target =
  | {
      stop: {};
    }
  | SectionRef;
export type ListId = string;
export type Body = Stmt[];

/**
 * Core program JSON (SPEC §5.1): what the preprocessor emits and the Dafny core consumes. The preprocessor only parses; every semantic check (references resolve, taint, bound names, ...) is the core's job, so this schema accepts programs that will fail lint. `src` is always the 1-based line in SKILL.md.
 */
export interface CoreProgram {
  skill: string;
  format: 1;
  entry: SectionId;
  params: {
    [k: string]: ParamValue;
  };
  limits: {
    run_timeout_ms: number;
    do_timeout_ms: number;
    deadline_ms: number;
    ask_context_tokens: number;
  };
  /**
   * Data sections used as lists (SPEC §3.6), by list id.
   */
  lists: {
    [k: string]: List;
  };
  /**
   * Instruction sections (SPEC §3.2), by section id. Prose-only sections are omitted.
   */
  sections: {
    [k: string]: Section;
  };
}
export interface List {
  /**
   * Display name, as written in the heading.
   */
  name: string;
  src: Src;
  items: (
    | {
        src: Src;
        action: {
          label: string;
          cmd: Parts;
        };
      }
    | {
        src: Src;
        value: string;
      }
  )[];
}
export interface Section {
  /**
   * Display name, as written in the heading.
   */
  name: string;
  src: Src;
  /**
   * SPEC §3.2.
   */
  guidance: string | null;
  body: Body;
}
export interface StmtRun {
  src: Src;
  run: RunBody;
  else: Else;
}
export interface RunBody {
  cmd: Parts;
  as?: Name;
}
/**
 * A reference to a section. `anchor` is present only for a real link `[text](#anchor)`: `given` is the anchor written, `expected` the GitHub slug of the link text. The core reports E-UNRESOLVED if they differ.
 */
export interface SectionRef {
  section: SectionId;
  anchor?: Anchor;
}
export interface Anchor {
  given: string;
  expected: string;
}
export interface StmtDo {
  src: Src;
  do: DoBody;
  else: Else;
}
/**
 * `then` is null for the `check COND else …` form (SPEC §4.2).
 */
export interface StmtCheck {
  src: Src;
  check: {
    cond: Cond;
    then: null | Target;
    else: Else;
  };
}
export interface StmtAsk {
  src: Src;
  ask: Ask;
}
/**
 * Exactly one of sections, yesno, one_of or score (SPEC §3.4, §4.7).
 */
export interface Ask {
  question: Parts;
  sure: number;
  else: Else;
  sections?: {
    src: Src;
    section: SectionId;
    anchor?: Anchor;
  }[];
  yesno?: {
    /**
     * `_yn` when the skill doesn't name it.
     */
    as: string;
  };
  one_of?: {
    list: ListId;
    as: Name;
  };
  /**
   * v1.1.
   */
  score?: {
    low: number;
    high: number;
    rubric: {
      src: Src;
      level: number;
      text: string;
    }[];
    as: Name;
  };
}
export interface StmtForEach {
  src: Src;
  for_each: {
    var: Name;
    list: ListId;
    body: Body;
  };
}
export interface StmtIfYes {
  src: Src;
  /**
   * Exactly one of run or do.
   */
  if_yes: {
    run?: RunBody;
    do?: DoBody;
    else: Else;
  };
}
export interface StmtThen {
  src: Src;
  then: SectionRef;
}
export interface StmtPage {
  src: Src;
  page: Parts;
}
export interface StmtHandOff {
  src: Src;
  hand_off: {};
}
export interface StmtStop {
  src: Src;
  stop: {};
}

export interface AskRequest {
  kind: "choice" | "yesno" | "score";
  /**
   * Rendered: trusted values pasted in, run outputs named in backticks (SPEC §3.5).
   */
  question: string;
  guidance: string | null;
  /**
   * @minItems 2
   */
  options: [
    {
      id: string;
      label: string;
      description: string | null;
    },
    {
      id: string;
      label: string;
      description: string | null;
    },
    ...{
      id: string;
      label: string;
      description: string | null;
    }[]
  ];
  /**
   * Exactly the run outputs the question names, redacted and truncated (SPEC §6.3).
   */
  context: {
    [k: string]: string;
  };
  timeout_ms: number;
}

export interface AskAnswer {
  probs: {
    [k: string]: number;
  };
  unassigned?: number;
  backend: string;
  model: string;
  ms: number;
}

/**
 * answers.yaml: a probs object keyed by option id (with optional `unassigned`), or `unsure`, `unavailable` or `invalid` to force that path.
 */
export interface FakesAnswers {
  [k: string]:
    | ("unsure" | "unavailable" | "invalid")
    | {
        [k: string]: number;
      };
}

/**
 * commands.yaml: how each command ends. An unmatched command is E-FAKE-UNMATCHED; no real command ever runs.
 */
export interface FakesCommands {
  [k: string]: {
    /**
     * null when it timed out.
     */
    exit: number | null;
    stdout?: string;
    stderr?: string;
    timed_out?: boolean;
  };
}

/**
 * One line of skop's JSON Lines output on stdout (SPEC §10). Every event has the common fields; each event name adds its own. Nothing else is allowed.
 */
export type Event = {
  [k: string]: unknown;
} & {
  /**
   * UTC, ISO 8601.
   */
  ts: string;
  run_id: string;
  skill: string;
  skill_hash: string;
  host: string;
  event:
    | "run_start"
    | "run"
    | "check_cmd"
    | "check"
    | "ask"
    | "effect_start"
    | "effect_end"
    | "would_do"
    | "would_page"
    | "handoff_page"
    | "transfer"
    | "outcome"
    | "handoff_record"
    | "error"
    | "warning"
    | "locked"
    | "stale_lock";
  section?: string;
  line?: number;
};
